app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    
    path('',views.home,name='home'),
]

manager/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('manager_dashboard/',views.manager_dashboard,name='manager_dashboard'),
    path('user_management/',views.user_management,name='user_management'),
    path('category_management/',views.category_management,name='category_management'),
    path('add_category',views.add_category,name='add_category'),
    path('order_management/',views.order_management,name='order_management'),
    path('product_management/',views.product_management,name='product_management'),
    path('variation_management',views.variation_management,name='variation_management'),
    path('admin_orders/', views.admin_order, name='admin_orders'),
    
    path('add_variation/', views.add_variation, name='add_variation'),
    path('update_variation/<int:variation_id>/',views.update_variation,name='update_variation'),
    path('delete_variation/<int:variation_id>/', views.delete_variation, name='delete_variation'),
    
    path('admin_change_password/', views.admin_change_password, name='admin_change_password'),
    
    path('user_ban/<int:user_id>/',views.user_ban,name='user_ban'),
    path('user_unban/<int:user_id>/',views.user_unban,name='user_unban'),
    path('delete_category/<int:category_id>/',views.delete_category,name='delete_category'),
    path('update_category/<int:category_id>/', views.update_category, name="update_category"),
    path('manager_cancel_order/<int:order_number>/', views.manager_cancel_order, name='manager_cancel_order'),
    path('accept_order/<int:order_number>/', views.accept_order, name='accept_order'),
    path('complete_order/<int:order_number>/', views.complete_order, name='complete_order'),
    path('cancel_order/<int:order_number>/', views.cancel_order, name='cancel_order'),
    path('add_product/',views.add_product,name='add_product'),
    path('delete_product/<int:product_id>/',views.delete_product,name='delete_product'),
    path('edit_product/<int:product_id>/',views.edit_product,name='edit_product'),
    
]
    

prjct/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

import manager

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/',include('accounts.urls')),
    path('store/',include('store.urls')),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('manager/',include('manager.urls')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models
from accounts.models import Accounts
from category.models import Category
from django.urls import reverse
from django.db.models import Avg, Count
# Create your models here.

class Product(models.Model):
    product_name    = models.CharField(max_length=200, unique=True)
    slug            = models.SlugField(max_length=200, unique=True)
    description     = models.TextField(max_length=500, blank=True)
    price           = models.IntegerField()
    images          = models.ImageField(upload_to='photos/products')
    stock           = models.IntegerField()
    is_available    = models.BooleanField(default=True)
    category        = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date    = models.DateTimeField(auto_now_add=True)
    modified_date   = models.DateTimeField(auto_now=True)
    
    
    def get_url(self):
        return reverse('product_details',args=[self.category.slug, self.slug])
    
    
    def __str__(self):
        return self.product_name
    
    def averageReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg
    
    def countReview(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
        count = 0 
        if reviews['count'] is not None:
            count = int(reviews['count'])
        return count

    
class VariationManager(models.Manager):
    def sizes(self):
        return super(VariationManager,self).filter(variation_category='size', is_active=True)
    
    
variation_category_choice = (
    ('size','size'),
)

class Variation(models.Model):
    product            = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value    = models.CharField(max_length=100)
    is_active          = models.BooleanField(default=True)
    created_date       = models.DateTimeField(auto_now=True)
    
    objects = VariationManager()
    
    def __str__(self):
        return self.variation_value 

    
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Accounts, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20,blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    
    def __str__(self):
        return self.subject
    
class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image =models.ImageField(upload_to='store/products',max_length=255)
    
    def __str__(self):
        return self.product.product_name
    
    class Meta:
        verbose_name='productgallery'
        verbose_name_plural ='product gallery'
    

manager/forms.py
from django import forms
from store.models import Product,Variation

class ProductForm(forms.ModelForm):
  
  class Meta:
     model = Product
     fields = ['product_name', 'slug', 'description', 'price', 'images', 'category', 'stock', 'is_available']
  
  def __init__(self, *args, **kwargs):
    super(ProductForm, self).__init__(*args, **kwargs)
    
    for field in self.fields:
      self.fields[field].widget.attrs['class'] = 'form-control'
    
    self.fields['is_available'].widget.attrs['class'] = 'ml-2 mt-1 form-check-input'
    


class VariationForm(forms.ModelForm):
  
  class Meta:
    model = Variation
    fields = ['product', 'variation_category', 'variation_value', 'is_active']
  
  def __init__(self, *args, **kwargs):
    super(VariationForm, self).__init__(*args, **kwargs)
    
    for field in self.fields:
      self.fields[field].widget.attrs['class'] = 'form-control'
      
    self.fields['is_active'].widget.attrs['class'] = 'ml-2 mt-1 form-check-input'

manager/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render,redirect
from accounts.models import  Accounts
from store.models import Product,Variation
from orders.models import Order
from category.models import Category
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import ProductForm,VariationForm
from django.contrib.auth.hashers import make_password,check_password
from django.contrib import messages

# Create your views here.
@never_cache
@login_required(login_url='login')
def manager_dashboard(request):
    if request.user.is_superadmin:

        user_count = Accounts.objects.filter(is_superadmin=False).count()
        product_count = Product.objects.all().count()
        order_count = Order.objects.filter(is_ordered=True).count()
        category_count = Category.objects.all().count()
        variation_count = Variation.objects.all().count()
        admin_order_count = Order.objects.filter(user__is_superadmin=True).count()
        

        context = {
            'user_count': user_count,
            'product_count': product_count,
            'order_count' : order_count,
            'category_count' : category_count,
            'variation_count' : variation_count,
            'admin_order_count' : admin_order_count
        }

        return render(request,'manager/manager_dashboard.html',context)
    else:
        return redirect('home')
    
@never_cache
@login_required(login_url='login')
def user_management(request):
    if request.method == "POST":
      key = request.POST['key']
      users = Accounts.objects.filter(Q(first_name__startswith=key) | Q(last_name__startswith=key) | Q(username__startswith=key) | Q(email__startswith=key)).order_by('id')
    else:
      users = Accounts.objects.filter(is_superadmin=False).order_by('id')

    paginator = Paginator(users,10)
    page = request.GET.get('page')
    paged_users = paginator.get_page(page)
    context = {
        'users' : paged_users
    }
    return render(request, 'manager/user_management.html',context)

def user_ban(request, user_id):
    user = Accounts.objects.get(id=user_id)
    user.is_active = False
    user.save()
    return redirect('user_management')

def user_unban(request, user_id):
    user = Accounts.objects.get(id=user_id)
    user.is_active = True
    user.save()
    return redirect('user_management')

# Product Management
@never_cache
@login_required(login_url='login')
def product_management(request):
  if request.method == "POST":
    key = request.POST['key']
    products = Product.objects.filter(Q(product_name__startswith=key) | Q(slug__startswith=key) | Q(category__category_name__startswith=key)).order_by('id')
  else:
    products = Product.objects.all().order_by('id')

  paginator = Paginator(products, 10)
  page = request.GET.get('page')
  paged_products = paginator.get_page(page)
  
  context = {
    'products': paged_products
  }
  return render(request, 'manager/product_management.html', context)

# Add Product
@never_cache
@login_required(login_url='login')
def add_product(request):
  if request.method == 'POST':
    form = ProductForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('product_management')
  else:
    form = ProductForm()
    context = {
      'form': form
    }
    return render(request, 'manager/add_product.html', context)

# Edit Product
@never_cache
@login_required(login_url='manager_login')
def edit_product(request, product_id):
  product = Product.objects.get(id=product_id)
  form = ProductForm(instance=product)
  
  if request.method == 'POST':
    try:
      form = ProductForm(request.POST, request.FILES, instance=product)
      if form.is_valid():
        form.save()
        
        return redirect('product_management')
    
    except Exception as e:
      raise e

  context = {
    'product': product,
    'form': form
  }
  return render(request, 'manager/edit_product.html', context)

# Delete Product
@never_cache
@login_required(login_url='manager_login')
def delete_product(request, product_id):
  product = Product.objects.get(id=product_id)
  product.delete()
  return redirect('product_management')

# Admin change password
@never_cache
@login_required(login_url='login')
def admin_change_password(request):
  if request.method == 'POST':
    current_user = request.user
    current_password = request.POST['current_password']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    
    if password == confirm_password:
      if check_password(current_password, current_user.password):
        if check_password(password, current_user.password):
          messages.warning(request, 'Current password and new password is same')
        else:
          hashed_password = make_password(password)
          current_user.password = hashed_password
          current_user.save()
          messages.success(request, 'Password changed successfully')
      else:
        messages.error(request, 'Wrong password')
    else:
      messages.error(request, 'Passwords does not match')
  
  return render(request, 'manager/admin_password.html')

# Manage Order
@never_cache
@login_required(login_url='login')
def order_management(request):
  if request.method =="POST":
    key = request.POST['key']
    orders = Order.objects.filter(Q(is_ordered=True), Q(order_number__startswith=key) | Q(user__email__startswith=key) | Q(first_name__startswith=key)).order_by('id')
  else:
    orders = Order.objects.filter(is_ordered=True).order_by('id')
    

  context = {
    'orders': orders
  }
  return render(request, 'manager/order_management.html', context)

# Cancel Order
@never_cache
@login_required(login_url='login')
def manager_cancel_order(request, order_number):
  order = Order.objects.get(order_number=order_number)
  order.status = 'Cancelled'
  order.save()
  
  return redirect('order_management')
  

# Accept Order
@never_cache
@login_required(login_url='login')
def accept_order(request, order_number):
  order = Order.objects.get(order_number=order_number)
  order.status = 'Shipped'
  order.save()
  
  return redirect('order_management')

# Complete Order
@never_cache
@login_required(login_url='login')
def complete_order(request, order_number):
  order = Order.objects.get(order_number=order_number)
  order.status = 'Delivered'
  order.save()
  
  return redirect('order_management')

def category_management(request):
    categories = Category.objects.all().order_by('id')

    context = {
        'categories' :categories
    }

    return render(request, 'manager/category_management.html',context)


def add_category(request):
    if request.method == 'POST':
        try:
            category_name = request.POST['category_name']
            category_slug = request.POST['category_slug']
            category_description = request.POST['category_description']
            
            categories = Category(
                category_name = category_name,
                slug = category_slug,
                description = category_description
            )
            
            categories.save()
            return redirect('category_management')
        except Exception as e:
            raise e
    return render(request, 'manager/add_category.html')

# Update Category
@never_cache
@login_required(login_url='login')
def update_category(request, category_id):
  try:
    categories = Category.objects.get(id=category_id)
    
    if request.method == 'POST':
      category_name = request.POST['category_name']
      category_slug = request.POST['category_slug']
      category_description = request.POST['category_description']
      
      categories.category_name = category_name
      categories.slug = category_slug
      categories.description = category_description
      categories.save()
      
      return redirect('category_management')
    
    context = {
      'category': categories
    }
    return render(request, 'manager/update_category.html', context)
    
  except Exception as e:
    raise e
    
       

@never_cache
@login_required(login_url='login')
def delete_category(request,category_id):
    categories = Category.objects.get(id=category_id)
    categories.delete()

    return redirect('category_management')
  
  # Manage Variation
@never_cache
@login_required(login_url='login')
def variation_management(request):
  if request.method == 'POST':
    keyword = request.POST['keyword']
    variations = Variation.objects.filter(Q(product__product_name__startswith=keyword) | Q(variation_category__startswith=keyword) | Q(variation_value__startswith=keyword)).order_by('id')
  
  else:
    variations = Variation.objects.all().order_by('id')
  
  paginator = Paginator(variations, 10)
  page = request.GET.get('page')
  paged_variations = paginator.get_page(page)
  
  context = {
    'variations': paged_variations
  }
  return render(request, 'manager/variation_management.html', context)


# Add Variation
@never_cache
@login_required(login_url='login')
def add_variation(request):
  
  if request.method == 'POST':
    form = VariationForm(request.POST)
    if form.is_valid():
      form.save()
      return redirect('variation_management')
  
  else:
    form = VariationForm()
  
  context = {
    'form': form
  }
  return render(request, 'manager/add_variation.html', context)


# Update Variation
@never_cache
@login_required(login_url='login')
def update_variation(request, variation_id):
  variation = Variation.objects.get(id=variation_id)
  
  if request.method == 'POST':
    form = VariationForm(request.POST ,instance=variation)
    if form.is_valid():
      form.save()
      return redirect('variation_management')
  
  else:
    form = VariationForm(instance=variation)
  
  context = {
    'variation': variation,
    'form': form
  }

templates/manager/add_category.html
{% extends 'base.html' %} {% block content %}
<section class="section-content padding-y bg">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-6">
        <h1 class="text-center h2 mb-4">Add Category</h1>
        <form action="{% url 'add_category' %}" method="POST">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="category_name">Category Name</label>
              <input type="text" class="form-control" id="category_name" name="category_name" placeholder="Enter a category name" required />
            </div>
            <div class="form-group col-md-6">
              <label for="category_slug">Category Slug</label>
              <input type="text" class="form-control" id="category_slug" name="category_slug" aria-describedby="category_slug" placeholder="Enter a category slug" required />
              <small id="category_slug" class="form-text text-muted">Format :- name: T Shirt, slug: t-shirt</small>
            </div>
          </div>
          <div class="form-group">
            <label for="category_description">Category Description</label>
            <textarea class="form-control" id="category_description" name="category_description" placeholder="Enter category description" row="100"></textarea>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/manager/add_product.html
{% extends 'base.html' %} 
{% block content %}

<section class="section-content padding-y bg" style=background-color:black;>
  <div class="container text-light">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Add Product</h1>
        <form action="{% url 'add_product' %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product_name }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Product Slug</label>
              {{ form.slug }}
              <!-- <small id="product_slug" class="form-text text-muted">Format :- name: ATX Jeans, slug: atx-jeans</small> -->
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Product Price</label>
              {{ form.price }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_image">Product Image</label>
              {{ form.images }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_stock">Product Stock</label>
              {{ form.stock }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_category">Category</label>
              {{ form.category }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Available</label>
              {{ form.is_available }}
            </div>
            

          </div>

          <div class="form-group">
            <label for="product_description">Product Description</label>
            {{ form.description }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/manager/add_variation.html
{% extends 'base.html' %}

{% block content %}
<section class="section-content padding-y bg" style=background-color:black;>
  <div class="container text-light">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Add Variation</h1>
        <form action="{% url 'add_variation' %}" method="POST">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Variation Category</label>
              {{ form.variation_category }}
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Variation Value</label>
              {{ form.variation_value }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Active</label>
              {{ form.is_active }}
            </div>
          <div class="text-center">
            <button type="submit" class="btn btn-light">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/manager/admin_orders.html
{% extends 'base.html' %}
{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content mt-3 bg">
  <div class="container">
    <h1 class="text-center h2 mb-4">My Orders</h1>
    <div class="d-flex mb-3 justify-content-end">
      {% comment %} <form action="{% url 'admin_orders' %}" class="search" method="POST">
        {% csrf_token %} 
        <div class="input-group w-100">
          <input type="text" class="form-control" style="width: 60%" placeholder="Search" name="keyword" />

          <div class="input-group-append">
            <button class="btn btn-dark" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>
      </form> {% endcomment %}
    </div>
    <div class="row">
      <aside class="col-md-3">
        <!--   SIDEBAR   -->
        <ul class="list-group">
            <a class="list-group-item btn btn-outline-dark" href="{% url 'manager_dashboard' %}"> Dashboard </a>
            <a class="list-group-item btn btn-outline-dark " href="{% url 'user_management' %}"> User Management </a>
            <a class="list-group-item btn btn-outline-dark" href="{% url 'product_management' %}"> Product Management </a>
            <a class="list-group-item btn btn-outline-dark" href="{% url 'order_management' %}"> Order Management </a>
            <a class="list-group-item btn btn-outline-dark " href="{% url 'category_management' %}"> Category Management </a>
            <a class="list-group-item btn btn-outline-dark" href="{% url 'variation_management' %}"> Variation Management </a>
            <a class="list-group-item btn btn-outline-dark active" href="{% url 'admin_orders' %}"> My Orders </a>
            <a class="list-group-item btn btn-outline-dark" href="{% url 'admin_change_password' %}"> Change Password </a>
        </ul>
        <br />
        <a class="btn btn-dark btn-block" href="{% url 'logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a>
        <!--   SIDEBAR .//END   -->
      </aside>
      <main class="col-md-9">
        <table class="table table-light">
          <thead>
            <tr>
              <th scope="col">Order </th>
              <th scope="col">User</th>
              <th scope="col">Billing Name</th>
              <th scope="col">Phone Number</th>
              <th scope="col">Order Total</th>
              <th scope="col">Order Status</th>
              <th scope="col">Order Cancel</th>
            </tr>
          </thead>
          <tbody>
            {% for order in orders %}
            <tr>
              <th scope="row"><a href="{% url 'order_details' order.order_number %}">{{ order.order_number }}</a></th>
              <td>{{ order.user }}</td>
              <td>{{ order.full_name }}</td>
              <td>{{ order.phone }}</td>
              <td>₹ {{ order.order_total }}</td>
              <td>
                {% if order.status == 'Cancelled' %}
                <span class="text-danger font-weight-bold">{{ order.status }}</span>
                {% elif order.status == 'Delivered' %}
                <span class="text-success font-weight-bold">{{ order.status }}</span>
                {% elif order.status == 'Pending' %}
                <span class="text-muted font-weight-bold">{{ order.status }}</span>
                {% else %} <span class="text-info font-weight-bold">{{ order.status }}</span>
                {% endif %}
              </td>
              <td>
                {% if order.status == 'Shipped' %}
                <a href="{% url 'cancel_order' order.order_number %}" class="btn btn-light btn-sm">Cancel</a>
                {% elif order.status == 'Pending' %}
                <a href="{% url 'cancel_order' order.order_number %}" class="btn btn-light btn-sm">Cancel</a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </main>
    </div>
    <!-- row.// -->
  </div>
  <div class="container">
    <div class="row">
      <aside class="col-md-3"></aside>
      <main class="col-md-9">
        <nav class="mt-4" aria-label="Page navigation sample">
          {% if orders.has_other_pages %}
          <ul class="pagination">
            {% if orders.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ orders.previous_page_number }}">Previous</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
            {% endif %} {% for page_number in orders.paginator.page_range %} {% if orders.number == page_number %}
            <li class="page-item active"><a class="page-link" href="#">{{ page_number }}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
            {% endif %} {% endfor %} {% if orders.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ orders.next_page_number }}">Next</a></li>
            {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
            {% endif %}
          </ul>
          {% endif %}
        </nav>
      </main>
    </div>
  </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock content %}

templates/manager/edit_product.html
{% extends 'base.html' %} 
{% block content %}

<section class="section-content padding-y bg" style= background-color:gray;>
  <div class="container text-light">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Edit Product</h1>
        <form action="{% url 'edit_product' product.id %}" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_product_name">Product Name</label>
              {{ form.product_name }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Product Slug</label>
              {{ form.slug }}
              <!-- <small id="product_slug" class="form-text text-muted">Format :- name: ATX Jeans, slug: atx-jeans</small> -->
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Product Price</label>
              {{ form.price }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_image">Product Image</label>
              {{ form.images }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_stock">Product Stock</label>
              {{ form.stock }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_category">Category</label>
              {{ form.category }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Available</label>
              {{ form.is_available }}
            </div>

          </div>

          <div class="form-group">
            <label for="product_description">Product Description</label>
            {{ form.description }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/manager/update_variation.html
{% extends 'base.html' %} 
{% block content %}


<section class="section-content padding-y bg" style=background-color:black;>
  <div class="container text-light">
    <div class="row d-flex justify-content-center">
      <div class="col-8">
        <h1 class="text-center h2 mb-4">Edit Variation</h1>
        <form action="{% url 'update_variation' variation.id %}" method="POST">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="id_name">Product Name</label>
              {{ form.product }}
            </div>
            <div class="form-group col-md-6">
              <label for="product_slug">Variation Category</label>
              {{ form.variation_category }}
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="product_price">Variation Value</label>
              {{ form.variation_value }}
            </div>
            <div class="form-group col-md-6">
              <label for="id_is_available">Active</label>
              {{ form.is_active }}
            </div>
          <div class="text-center">
            <button type="submit" class="btn btn-light ">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}